ALTER TABLE MayIn
ADD Edit bit 
ALTER TABLE MayIn
ADD DEFAULT 0 FOR Edit


ALTER TABLE Khu
ADD Edit bit 
ALTER TABLE Khu
ADD DEFAULT 0 FOR Edit

ALTER TABLE KhachHang
ADD Edit bit 
ALTER TABLE KhachHang
ADD DEFAULT 0 FOR Edit

ALTER TABLE MenuKhuyenMai
ADD Edit bit 
ALTER TABLE MenuKhuyenMai
ADD DEFAULT 0 FOR Edit

ALTER TABLE MenuKichThuocMon
ADD Edit bit 
ALTER TABLE MenuKichThuocMon
ADD DEFAULT 0 FOR Edit

ALTER TABLE LichBieuDinhKy
ADD Edit bit 
ALTER TABLE LichBieuDinhKy
ADD DEFAULT 0 FOR Edit

ALTER TABLE NhaCungCap
ADD Edit bit 
ALTER TABLE NhaCungCap
ADD DEFAULT 0 FOR Edit

ALTER TABLE Kho
ADD Edit bit 
ALTER TABLE Kho
ADD DEFAULT 0 FOR Edit

ALTER TABLE MenuLoaiGia
ADD Edit bit 
ALTER TABLE MenuLoaiGia
ADD DEFAULT 0 FOR Edit

ALTER TABLE LoaiKhachHang
ADD Edit bit 
ALTER TABLE LoaiKhachHang
ADD DEFAULT 0 FOR Edit

ALTER TABLE Quyen
ADD Edit bit 
ALTER TABLE Quyen
ADD DEFAULT 0 FOR Edit

ALTER TABLE NhomChucNang
ADD Edit bit 
ALTER TABLE NhomChucNang
ADD DEFAULT 0 FOR Edit

ALTER TABLE QuyenNhanVien
ADD Edit bit 
ALTER TABLE QuyenNhanVien
ADD DEFAULT 0 FOR Edit

ALTER TABLE QuyenNhanVien
ADD Visual bit 
ALTER TABLE QuyenNhanVien
ADD DEFAULT 1 FOR Visual

ALTER TABLE QuyenNhanVien
ADD Deleted bit 
ALTER TABLE QuyenNhanVien
ADD DEFAULT 0 FOR Deleted

ALTER TABLE CHITIETQUYEN
ADD Edit bit 
ALTER TABLE CHITIETQUYEN
ADD DEFAULT 0 FOR Edit