DROP VIEW BAOCAOTONKHO
GO
CREATE VIEW BAOCAOTONKHO
AS
SELECT  
	
	CASE
		WHEN M.DonViID = 1 THEN  'Cái, Lon, ...'
		WHEN M.DonViID = 2 THEN  'Kg' 
		WHEN M.DonViID = 3 THEN  'Lít'
		WHEN M.DonViID = 4 THEN  'Giờ'
	END As DonViTinh,					
	M.TenDai As TenBaoCao,       
	CASE
		WHEN T.DonViID = 1 THEN ISNULL(T.SoLuongTon, 0)
		WHEN T.DonViID = 2 THEN CAST(ISNULL(T.SoLuongTon, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 3 THEN CAST(ISNULL(T.SoLuongTon, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 4 THEN CAST(ISNULL(T.SoLuongTon, 0) / 3600.000 AS DECIMAL(10,3)) 					
		ELSE CAST(ISNULL(T.SoLuongTon, 0) AS DECIMAL(10,0)) 
	END
	AS SoluongTon,	
	CASE
		WHEN T.DonViID = 1 THEN ISNULL(T.SoLuongBan, 0)
		WHEN T.DonViID = 2 THEN CAST(ISNULL(T.SoLuongBan, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 3 THEN CAST(ISNULL(T.SoLuongBan, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 4 THEN CAST(ISNULL(T.SoLuongBan, 0) / 3600.000 AS DECIMAL(10,3)) 					
		ELSE CAST(ISNULL(T.SoLuongBan, 0) AS DECIMAL(10,0)) 
	END
	AS SoLuongBan,
	CASE
		WHEN T.DonViID = 1 THEN ISNULL(T.SoLuongNhap, 0)
		WHEN T.DonViID = 2 THEN CAST(ISNULL(T.SoLuongNhap, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 3 THEN CAST(ISNULL(T.SoLuongNhap, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 4 THEN CAST(ISNULL(T.SoLuongNhap, 0) / 3600.000 AS DECIMAL(10,3)) 					
		ELSE CAST(ISNULL(T.SoLuongNhap, 0) AS DECIMAL(10,0)) 
	END
	AS SoLuongNhap,
	CASE
		WHEN T.DonViID = 1 THEN ISNULL(T.SoLuongChuyen, 0)
		WHEN T.DonViID = 2 THEN CAST(ISNULL(T.SoLuongChuyen, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 3 THEN CAST(ISNULL(T.SoLuongChuyen, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 4 THEN CAST(ISNULL(T.SoLuongChuyen, 0) / 3600.000 AS DECIMAL(10,3)) 					
		ELSE CAST(ISNULL(T.SoLuongChuyen, 0) AS DECIMAL(10,0)) 
	END
	AS SoLuongChuyen,	
	CASE
		WHEN T.DonViID = 1 THEN ISNULL(T.SoLuongHu, 0)
		WHEN T.DonViID = 2 THEN CAST(ISNULL(T.SoLuongHu, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 3 THEN CAST(ISNULL(T.SoLuongHu, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 4 THEN CAST(ISNULL(T.SoLuongHu, 0) / 3600.000 AS DECIMAL(10,3)) 					
		ELSE CAST(ISNULL(T.SoLuongHu, 0) AS DECIMAL(10,0)) 
	END
	AS SoLuongHu,
	CASE
		WHEN T.DonViID = 1 THEN ISNULL(T.SoLuongDieuChinh, 0)
		WHEN T.DonViID = 2 THEN CAST(ISNULL(T.SoLuongDieuChinh, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 3 THEN CAST(ISNULL(T.SoLuongDieuChinh, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 4 THEN CAST(ISNULL(T.SoLuongDieuChinh, 0) / 3600.000 AS DECIMAL(10,3)) 					
		ELSE CAST(ISNULL(T.SoLuongDieuChinh, 0) AS DECIMAL(10,0)) 
	END
	AS SoLuongDieuChinh,
	CASE
		WHEN T.DonViID = 1 THEN ISNULL(T.SoLuongMat, 0)
		WHEN T.DonViID = 2 THEN CAST(ISNULL(T.SoLuongMat, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 3 THEN CAST(ISNULL(T.SoLuongMat, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 4 THEN CAST(ISNULL(T.SoLuongMat, 0) / 3600.000 AS DECIMAL(10,3)) 					
		ELSE CAST(ISNULL(T.SoLuongMat, 0) AS DECIMAL(10,0)) 
	END
	AS SoLuongMat,
	M.MonID,
	CASE
		WHEN T.DonViID = 1 THEN ISNULL(BN.SoLuongBan, 0)
		WHEN T.DonViID = 2 THEN CAST(ISNULL(BN.SoLuongBan, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 3 THEN CAST(ISNULL(BN.SoLuongBan, 0) / 1000.000 AS DECIMAL(10,3)) 
		WHEN T.DonViID = 4 THEN CAST(ISNULL(BN.SoLuongBan, 0) / 3600.000 AS DECIMAL(10,3)) 					
		ELSE CAST(ISNULL(T.SoLuongMat, 0) AS DECIMAL(10,0)) 
	END AS SLBanNgay,
	BN.NgayBan	
	FROM	dbo.MENUMON AS M LEFT OUTER JOIN
			dbo.TONKHOTONG AS T ON M.MonID = T.MonID
			LEFT OUTER JOIN
			(
				SELECT CAST(BH.NgayBan AS DATE) AS NgayBan, M.MonID, SUM(CTBH.SoLuongBan*KTM.KichThuocLoaiBan) AS  SoLuongBan
				FROM CHITIETBANHANG CTBH
				INNER JOIN BANHANG BH ON BH.BanHangID = CTBH.BanHangID
				INNER JOIN MENUKICHTHUOCMON KTM ON KTM.KichThuocMonID = CTBH.KichThuocMonID
				INNER JOIN MENUMON M ON M.MonID = KTM.MonID
				WHERE ChoPhepTonKho = 1
				GROUP BY M.MonID, CAST(BH.NgayBan AS DATE)	
			 UNION 
				SELECT CAST(BH.NgayBan AS DATE) AS NgayBan, DL.MonID, SUM(CTBH.SoLuongBan * DL.SoLuong * DL.KichThuocBan) AS SoLuongBan
				FROM CHITIETBANHANG CTBH 
				INNER JOIN BANHANG BH ON BH.BanHangID = CTBH.BanHangID
				INNER JOIN MENUKICHTHUOCMON KTM ON KTM.KichThuocMonID = CTBH.KichThuocMonID
				INNER JOIN DINHLUONG DL ON DL.KichThuocMonChinhID = KTM.KichThuocMonID
				INNER JOIN MENUMON M ON M.MonID = DL.MonID
				WHERE ChoPhepTonKho = 0
				GROUP BY DL.MonID, CAST(BH.NgayBan AS DATE)	
			) AS BN ON BN.MonID = T.MonID
	Where SLMonChoPhepTonKho > 0
GO


