DROP VIEW BAOCAONHANVIEN
GO
CREATE VIEW BAOCAONHANVIEN
AS
SELECT 
	ISNULL(MAX(BH.BanHangID), 0) As ID,
	CAST(NgayBan AS DATE) AS NgayBan, NV.TenNhanVien,
	COUNT(BH.BanHangID) AS SoHoaDon,
	SUM(CTBH.SoLuongBan) AS SoLuongBan,
	SUM(BH.TongTien) As TongTien
	FROM BANHANG BH 
	INNER JOIN NHANVIEN NV ON BH.NhanVienID = NV.NhanVienID
	INNER JOIN CHITIETBANHANG CTBH ON BH.BanHangID = CTBH.BanHangID
	GROUP BY NV.TenNhanVien, CAST(NgayBan AS DATE)	